[tool.pyright]
pythonVersion = "3.11"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = ".", extraPaths = [
    "/usr/lib/python3.11/site-packages",
  ] },
]

reportUnusedImport = false

[tool.ruff]
# extend = "~/.config/ruff/pyproject.toml"  # Don't override system-wide default ruff config
extend = "../ruff/pyproject.toml"           # For this project, instead use the one already in the repo

[tool.ruff.lint]
extend-ignore = ["INP001"]
