customCommands:
  - key: "C"
    command: "git cz c"
    description: "Commit with commitizen"
    context: "files"
    loadingText: "Opening commitizen commit tool"
    subprocess: true
  - key: "<c-p>"
    command: "git remote prune {{.SelectedRemote.Name}}"
    context: "remotes"
    loadingText: "Pruning..."
    description: "Prune deleted remote branches"
os:
  editPreset: nvim-remote
gui:
  nerdFontsVersion: "3"
  expandFocusedSidePanel: true # accordion effect
  # Whether to show the divergence from the base branch in the branches view.
  showDivergenceFromBaseBranch: arrowAndNumber # or 'onlyArrow', default 'none'
  # statusPanelView: allBranchesLog # default 'dashboard'
git:
  # parseEmoji: true # render emoji strings in commit messages, e.g. `:sparkles:` -> ✨️
  paging:
    # use either externalDiffCommand OR pager
    externalDiffCommand: difft --color=always # --display=inline
    # colorArg: always
    # pager: diff-so-fancy
